server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/note_taker
    username: postgres
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      boot:
        allow_jdbc_metadata_access: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
